from libs.log.log import log
from libs.conifg import (RootName,Version,VersionType,Author,GitHubUrl,BiliBiliUrl)
log('This is a test message')
log(RootName)
log(Version)
log(VersionType)
log(Author)
log(GitHubUrl)
log(BiliBiliUrl)
log('This is a test message','warn')
log(RootName,'warn')
log(Version,'warn')
log(VersionType,'warn')
log(Author,'warn')
log(GitHubUrl,'warn')
log(BiliBiliUrl,'warn')